using Microsoft.EntityFrameworkCore;
using SmartPort.Application.Interfaces;
using SmartPort.Domain.Enums;
using SmartPort.Infrastructure.Persistence;

namespace SmartPort.Infrastructure.Services;

public class DashboardService : IDashboardService
{
    private readonly SmartPortDbContext _db;

    public DashboardService(SmartPortDbContext db) => _db = db;

    public async Task<DashboardSummaryDto> GetDashboardSummaryAsync()
    {
        var now = DateTime.UtcNow;
        var today = now.Date;

        // Vessels
        var vessels = await _db.Vessels.Where(v => !v.IsDeleted).ToListAsync();
        var inPort    = vessels.Where(v => v.IsCurrentlyInPort).ToList();
        var arriving  = vessels.Where(v => v.Status == VesselStatus.Approaching || v.Status == VesselStatus.AtAnchor).ToList();
        var arrivingToday = vessels.Where(v => v.EstimatedTimeOfArrival.HasValue && v.EstimatedTimeOfArrival.Value.Date == today).ToList();

        // Berths
        var berths = await _db.Berths.Where(b => !b.IsDeleted).ToListAsync();
        var berthAssignments = await _db.BerthAssignments
            .Include(a => a.Vessel)
            .Where(a => a.ActualDeparture == null && a.PlannedDeparture >= now.AddHours(-2))
            .ToListAsync();

        // Yard
        var yardBlocks = await _db.YardBlocks.Where(y => y.IsActive).ToListAsync();
        var totalCapacity = yardBlocks.Sum(y => y.TotalCapacityTEU);
        var totalOccupied = yardBlocks.Sum(y => y.CurrentOccupancyTEU);

        // Containers
        var containersInYard = await _db.Containers.CountAsync(c => c.Status == ContainerStatus.InYard && !c.IsDeleted);
        var dwellAlerts = await _db.Containers.CountAsync(c => c.IsDwellAlertRaised && !c.IsDeleted);

        // Gate/Trucks
        var gates = await _db.Gates.Where(g => !g.IsDeleted).ToListAsync();
        var trucksInQueue = await _db.Trucks.CountAsync(t => t.Status == TruckStatus.InQueue && !t.IsDeleted);
        var trucksInYard  = await _db.Trucks.CountAsync(t => t.Status == TruckStatus.InYard  && !t.IsDeleted);

        // Incidents
        var openIncidents     = await _db.Incidents.CountAsync(i => i.Status != IncidentStatus.Resolved && i.Status != IncidentStatus.Closed && !i.IsDeleted);
        var criticalIncidents = await _db.Incidents.CountAsync(i => i.Severity == IncidentSeverity.Critical && i.Status != IncidentStatus.Resolved && !i.IsDeleted);
        var activeAlerts      = await _db.Alerts.CountAsync(a => a.Status == AlertStatus.Active && !a.IsDeleted);
        var pendingRecs       = await _db.Recommendations.CountAsync(r => r.Status == RecommendationStatus.Pending && !r.IsDeleted);

        // Today's throughput (from metrics)
        var todayMetric = await _db.OperationalMetrics
            .Where(m => m.MetricDate == today && m.MetricType == "DailyThroughputTEU")
            .FirstOrDefaultAsync();

        // Avg Turnaround (last 7 days)
        var recentTurnaround = await _db.OperationalMetrics
            .Where(m => m.MetricDate >= today.AddDays(-7) && m.MetricType == "AverageTurnaroundHours")
            .AverageAsync(m => (decimal?)m.Value) ?? 32;

        var craneProductivity = await _db.OperationalMetrics
            .Where(m => m.MetricDate >= today.AddDays(-7) && m.MetricType == "CraneProductivity")
            .AverageAsync(m => (decimal?)m.Value) ?? 24;

        var truckTurnaround = await _db.OperationalMetrics
            .Where(m => m.MetricDate >= today.AddDays(-7) && m.MetricType == "TruckTurnaround")
            .AverageAsync(m => (decimal?)m.Value) ?? 45;

        // Throughput trend (14 days)
        var throughputTrend = await _db.OperationalMetrics
            .Where(m => m.MetricDate >= today.AddDays(-14) && m.MetricType == "DailyThroughputTEU")
            .OrderBy(m => m.MetricDate)
            .Select(m => new KpiTrendDto { Date = m.MetricDate, Value = m.Value, MetricType = m.MetricType, Label = m.MetricDate.ToString("dd MMM") })
            .ToListAsync();

        // Alert list
        var alertsList = await _db.Alerts
            .Where(a => a.Status == AlertStatus.Active && !a.IsDeleted)
            .OrderByDescending(a => a.Severity)
            .ThenByDescending(a => a.CreatedAt)
            .Take(6)
            .Select(a => new AlertDto
            {
                Id = a.Id, AlertType = a.AlertType, Status = a.Status, Severity = a.Severity,
                Title = a.Title, Message = a.Message, CreatedAt = a.CreatedAt, IsAutoGenerated = a.IsAutoGenerated
            })
            .ToListAsync();

        // Top recommendations
        var topRecs = await _db.Recommendations
            .Where(r => r.Status == RecommendationStatus.Pending && !r.IsDeleted)
            .OrderByDescending(r => r.Priority)
            .ThenByDescending(r => r.CreatedAt)
            .Take(3)
            .Select(r => new RecommendationDto
            {
                Id = r.Id, Type = r.Type, Status = r.Status, Priority = r.Priority,
                Title = r.Title, Summary = r.Summary, SuggestedAction = r.SuggestedAction,
                ImpactEstimate = r.ImpactEstimate, IsAIGenerated = r.IsAIGenerated, CreatedAt = r.CreatedAt
            })
            .ToListAsync();

        // Vessel lists
        var inPortList = inPort.Select(v => new VesselListDto
        {
            Id = v.Id, Name = v.Name, IMONumber = v.IMONumber, ShippingLine = v.ShippingLine,
            VesselType = v.VesselType, Status = v.Status, FlagCode = v.FlagCode,
            VoyageNumber = v.VoyageNumber, ETD = v.EstimatedTimeOfDeparture,
            DelayMinutes = v.DelayMinutes, Agent = v.Agent
        }).ToList();

        var arrivingList = arriving.Select(v => new VesselListDto
        {
            Id = v.Id, Name = v.Name, IMONumber = v.IMONumber, ShippingLine = v.ShippingLine,
            VesselType = v.VesselType, Status = v.Status, FlagCode = v.FlagCode,
            VoyageNumber = v.VoyageNumber, ETA = v.EstimatedTimeOfArrival, Agent = v.Agent
        }).ToList();

        // Berth statuses
        var berthStatuses = berths.Select(b =>
        {
            var currentAssignment = berthAssignments.FirstOrDefault(a => a.BerthId == b.Id);
            return new BerthStatusDto
            {
                Id = b.Id, Code = b.Code, Name = b.Name, Terminal = b.Terminal,
                BerthType = b.BerthType, Status = b.Status,
                Length = b.Length, MaxDraught = b.MaxDraught,
                CurrentVesselName = currentAssignment?.Vessel?.Name,
                CurrentVesselETD = currentAssignment?.PlannedDeparture,
                UtilisationPercent30Day = b.UtilisationPercent30Day,
                HasCranes = b.HasCranes, CraneCount = b.CraneCount
            };
        }).ToList();

        // Yard block statuses
        var yardStatuses = yardBlocks.Select(y => new YardBlockStatusDto
        {
            Id = y.Id, BlockCode = y.BlockCode, Terminal = y.Terminal, Zone = y.Zone,
            TotalCapacityTEU = y.TotalCapacityTEU, CurrentOccupancyTEU = y.CurrentOccupancyTEU,
            OccupancyPercent = y.OccupancyPercent,
            IsReeferBlock = y.IsReeferBlock, IsHazardousBlock = y.IsHazardousBlock,
            IsNearCapacity = y.IsNearCapacity, IsCritical = y.IsCritical
        }).ToList();

        return new DashboardSummaryDto
        {
            VesselsInPort = inPort.Count,
            VesselsExpectedToday = arrivingToday.Count,
            VesselsAtAnchor = vessels.Count(v => v.Status == VesselStatus.AtAnchor),
            VesselsDelayed = vessels.Count(v => v.DelayMinutes.HasValue && v.DelayMinutes > 0),
            BerthsOccupied = berths.Count(b => b.Status == BerthStatus.Occupied),
            BerthsAvailable = berths.Count(b => b.Status == BerthStatus.Available),
            BerthsUnderMaintenance = berths.Count(b => b.Status == BerthStatus.UnderMaintenance),
            BerthUtilisationPercent = berths.Count > 0 ? Math.Round((decimal)berths.Count(b => b.Status == BerthStatus.Occupied) / berths.Count * 100, 1) : 0,
            ContainersInYard = containersInYard,
            DwellAlertContainers = dwellAlerts,
            YardOccupancyPercent = totalCapacity > 0 ? Math.Round((decimal)totalOccupied / totalCapacity * 100, 1) : 0,
            ThroughputTodayTEU = (int)(todayMetric?.Value ?? 0),
            TrucksInQueue = trucksInQueue,
            TrucksInYard = trucksInYard,
            GatesOperational = gates.Count(g => g.IsOperational),
            OpenIncidents = openIncidents,
            CriticalIncidents = criticalIncidents,
            ActiveAlerts = activeAlerts,
            PendingRecommendations = pendingRecs,
            AverageTurnaroundHours = Math.Round(recentTurnaround, 1),
            CraneProductivity = Math.Round(craneProductivity, 1),
            TruckTurnaroundMinutes = Math.Round(truckTurnaround, 0),
            VesselsInPortList = inPortList,
            ArrivingVessels = arrivingList,
            ActiveAlertsList = alertsList,
            TopRecommendations = topRecs,
            BerthStatuses = berthStatuses,
            YardBlockStatuses = yardStatuses,
            ThroughputTrend = throughputTrend
        };
    }

    public async Task<IEnumerable<KpiTrendDto>> GetKpiTrendsAsync(int days = 30)
    {
        var from = DateTime.UtcNow.Date.AddDays(-days);
        return await _db.OperationalMetrics
            .Where(m => m.MetricDate >= from && m.MetricType == "DailyThroughputTEU")
            .OrderBy(m => m.MetricDate)
            .Select(m => new KpiTrendDto
            {
                Date = m.MetricDate,
                Value = m.Value,
                MetricType = m.MetricType,
                Label = m.MetricDate.ToString("dd MMM")
            })
            .ToListAsync();
    }
}
