using SmartPort.Domain.Enums;

namespace SmartPort.Domain.Entities;

/// <summary>
/// Represents an operational incident raised within the port system.
/// </summary>
public class Incident : BaseEntity
{
    public string ReferenceNumber { get; set; } = string.Empty;   // e.g. INC-2025-00124
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;

    public IncidentCategory Category { get; set; }
    public IncidentSeverity Severity { get; set; }
    public IncidentStatus Status { get; set; }

    // ─── Context ─────────────────────────────────────────────────────────
    public int? VesselId { get; set; }
    public int? BerthId { get; set; }
    public string? Location { get; set; }
    public string? Terminal { get; set; }

    // ─── People ───────────────────────────────────────────────────────────
    public string ReportedBy { get; set; } = string.Empty;
    public string? AcknowledgedBy { get; set; }
    public string? AssignedTo { get; set; }
    public string? ResolvedBy { get; set; }

    // ─── Timeline ────────────────────────────────────────────────────────
    public DateTime OccurredAt { get; set; }
    public DateTime? AcknowledgedAt { get; set; }
    public DateTime? ResolvedAt { get; set; }
    public DateTime? TargetResolutionTime { get; set; }
    public bool IsOverdue => TargetResolutionTime.HasValue && DateTime.UtcNow > TargetResolutionTime && Status != IncidentStatus.Resolved;

    // ─── Resolution ──────────────────────────────────────────────────────
    public string? RootCause { get; set; }
    public string? ResolutionNotes { get; set; }
    public string? CorrectiveAction { get; set; }
    public bool RequiresFollowUp { get; set; }

    // ─── Navigation ──────────────────────────────────────────────────────
    public virtual Vessel? Vessel { get; set; }
    public virtual Berth? Berth { get; set; }
    public virtual ICollection<IncidentUpdate> Updates { get; set; } = new List<IncidentUpdate>();
}

// ─────────────────────────────────────────────────────────────────────────────

/// <summary>
/// Represents a status update / log entry against an incident.
/// </summary>
public class IncidentUpdate : BaseEntity
{
    public int IncidentId { get; set; }
    public string UpdatedBy { get; set; } = string.Empty;
    public IncidentStatus NewStatus { get; set; }
    public string Note { get; set; } = string.Empty;
    public virtual Incident Incident { get; set; } = null!;
}

// ─────────────────────────────────────────────────────────────────────────────

/// <summary>
/// Represents a system-generated or user-raised alert requiring attention.
/// </summary>
public class Alert : BaseEntity
{
    public AlertType AlertType { get; set; }
    public AlertStatus Status { get; set; }
    public string Title { get; set; } = string.Empty;
    public string Message { get; set; } = string.Empty;
    public IncidentSeverity Severity { get; set; }

    // ─── Source ──────────────────────────────────────────────────────────
    public string? SourceSystem { get; set; }   // AI, Manual, AIS, SARS, Weather
    public int? RelatedVesselId { get; set; }
    public int? RelatedBerthId { get; set; }
    public int? RelatedContainerId { get; set; }
    public int? RelatedIncidentId { get; set; }

    // ─── Handling ────────────────────────────────────────────────────────
    public string? AcknowledgedBy { get; set; }
    public DateTime? AcknowledgedAt { get; set; }
    public string? ResolvedBy { get; set; }
    public DateTime? ResolvedAt { get; set; }
    public DateTime? ExpiresAt { get; set; }
    public bool IsAutoGenerated { get; set; }

    // ─── Navigation ──────────────────────────────────────────────────────
    public virtual Vessel? RelatedVessel { get; set; }
    public virtual Container? RelatedContainer { get; set; }
}

// ─────────────────────────────────────────────────────────────────────────────

/// <summary>
/// An AI/rules-engine generated recommendation for operational improvement.
/// </summary>
public class Recommendation : BaseEntity
{
    public RecommendationType Type { get; set; }
    public RecommendationStatus Status { get; set; }
    public IncidentSeverity Priority { get; set; }

    public string Title { get; set; } = string.Empty;
    public string Summary { get; set; } = string.Empty;
    public string DetailedRationale { get; set; } = string.Empty;
    public string SuggestedAction { get; set; } = string.Empty;
    public string? ImpactEstimate { get; set; }

    // ─── Source context ──────────────────────────────────────────────────
    public int? RelatedVesselId { get; set; }
    public int? RelatedBerthId { get; set; }
    public string? TriggerMetric { get; set; }
    public decimal? TriggerValue { get; set; }
    public decimal? ThresholdValue { get; set; }

    // ─── Handling ────────────────────────────────────────────────────────
    public string? ActedOnBy { get; set; }
    public DateTime? ActedOnAt { get; set; }
    public string? ActedOnNotes { get; set; }
    public DateTime? ExpiresAt { get; set; }
    public bool IsAIGenerated { get; set; } = true;

    public virtual Vessel? RelatedVessel { get; set; }
    public virtual Berth? RelatedBerth { get; set; }
}
