using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SmartPort.Application.DTOs;
using SmartPort.Application.Interfaces;
using SmartPort.Infrastructure.Services;
using SmartPort.Shared.Constants;

namespace SmartPort.Web.Controllers;

[Authorize(Policy = Policies.CanAccessGeminiAgent)]
public class GeminiAgentController : Controller
{
    private static readonly List<GeminiAgentHistoryItem> History = new();
    private readonly IConfiguration _configuration;
    private readonly IAgentNarrativeService _narrative;
    private readonly ISmartPortCopilotChatService _copilot;
    private readonly IExecutionPlanService _plans;
    private readonly IFleetDriverQueueService _queue;

    public GeminiAgentController(IConfiguration configuration, IAgentNarrativeService narrative, ISmartPortCopilotChatService copilot, IExecutionPlanService plans, IFleetDriverQueueService queue)
    {
        _configuration = configuration; _narrative = narrative; _copilot = copilot; _plans = plans; _queue = queue;
    }

    [HttpGet("/gemini-agent")]
    [HttpGet("/agent/gemini")]
    public async Task<IActionResult> Index()
    {
        var summary = await _queue.GetFleetSummaryAsync();
        ViewBag.Status = _narrative.GetStatus();
        ViewBag.GeminiApiKeyConfigured = !string.IsNullOrWhiteSpace(_configuration["GEMINI_API_KEY"] ?? _configuration["Gemini:ApiKey"]);
        ViewBag.GeminiEnabled = _configuration["Gemini:Enabled"] ?? "false";
        ViewBag.GeminiMode = _configuration["Gemini:Mode"] ?? "Hybrid";
        ViewBag.GeminiModel = _configuration["Gemini:Model"] ?? "gemini-2.5-flash";
        ViewBag.History = History.OrderByDescending(h => h.GeneratedAtUtc).Take(6).ToList();
        return View(summary);
    }

    [HttpPost("/gemini-agent/generate")]
    [IgnoreAntiforgeryToken]
    public async Task<IActionResult> Generate(string briefType = "Gemini Operations Brief")
    {
        var summary = await _queue.GetFleetSummaryAsync();
        var plan = await _plans.GeneratePlanAsync($"{briefType} · human-approved demo plan");
        var prompt = briefType switch
        {
            "Fleet Owner Action Plan" => "Generate a fleet owner action plan for the current Smart Port queue. Include driver notifications and approvals.",
            "Driver Instructions" => "Generate safe driver instructions for the current Smart Port queue, staging, and gate call-forward.",
            "Judge Demo Summary" => "Prepare a two-minute judge demo summary showing public site to audit trail loop.",
            "Risk & Governance Review" => "Review AI governance, human approval, synthetic data boundaries, and pilot connector readiness.",
            _ => "Generate a Gemini operations brief for gate pressure, berth readiness, idling impact, and next actions."
        };
        var response = await _copilot.GenerateResponseAsync(prompt);
        var generatedBy = response.GeneratedBy.Contains("Gemini", StringComparison.OrdinalIgnoreCase) ? "Generated by Gemini" : "Local Fallback Active";
        History.Add(new GeminiAgentHistoryItem(briefType, generatedBy, response.ShortAnswer, response.RecommendedAction, plan.PlanId, DateTime.UtcNow));
        TempData["Success"] = $"{briefType} generated. {generatedBy}. Audit event saved for this demo session.";
        return Redirect("/gemini-agent");
    }
}

public sealed record GeminiAgentHistoryItem(string BriefType, string GeneratedBy, string Summary, string RecommendedAction, string PlanId, DateTime GeneratedAtUtc);

[Authorize]
public class DemoTourController : Controller
{
    [HttpGet("/demo-tour")]
    public IActionResult Index() => View();
}

[Authorize(Policy = Policies.CanAccessReports)]
public class EnterpriseReadinessController : Controller
{
    [HttpGet("/enterprise-readiness")]
    [HttpGet("/pilot-readiness/enhanced")]
    public IActionResult Index() => View();
}
