using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SmartPort.Infrastructure.Services;
using SmartPort.Shared.Constants;

namespace SmartPort.Web.Controllers;

/// <summary>
/// Cross-domain reasoning surface. The engine LINKS congestion, gate backlog, berth,
/// emissions and disruption signals into ONE prioritised, quantified execution
/// recommendation. The page load is deterministic only (no LLM call); the optional
/// Gemini enhancement is action-triggered. Every generation and every Approve / Modify /
/// Reject decision is written to the immutable decision audit trail.
/// </summary>
[Authorize(Policy = Policies.CanAccessGeminiAgent)]
public class ReasoningController : Controller
{
    private readonly ICrossDomainReasoningService _reasoning;
    private readonly IDecisionAuditService _audit;

    public ReasoningController(ICrossDomainReasoningService reasoning, IDecisionAuditService audit)
    {
        _reasoning = reasoning;
        _audit = audit;
    }

    // GET /reasoning — deterministic only, safe to render on load.
    [HttpGet("/reasoning")]
    [HttpGet("/cross-domain")]
    public async Task<IActionResult> Index()
    {
        var rec = await _reasoning.GetDeterministicAsync();
        ViewBag.Audit = _audit.Recent(20);
        return View(rec);
    }

    // POST /reasoning/generate — action-triggered; applies optional Gemini enhancement.
    [HttpPost("/reasoning/generate")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Generate(CancellationToken ct)
    {
        var rec = await _reasoning.GenerateAsync(ActorName(), allowGemini: true, ct);
        ViewBag.Audit = _audit.Recent(20);
        TempData["Success"] = rec.UsedGemini
            ? "Cross-domain recommendation generated with Gemini enhancement. Audit entry saved."
            : "Cross-domain recommendation generated by the deterministic engine. Audit entry saved.";
        return View("Index", rec);
    }

    // POST /reasoning/decide — record an Approve / Modify / Reject decision against a recommendation.
    [HttpPost("/reasoning/decide")]
    [ValidateAntiForgeryToken]
    public IActionResult Decide(string recId, string decision, string? headline, string? impact, string? note)
    {
        var normalised = decision?.Trim().ToLowerInvariant() switch
        {
            "approved" or "approve" => "Approved",
            "modified" or "modify" => "Modified",
            "rejected" or "reject" => "Rejected",
            _ => "Logged"
        };

        var reasoning = string.IsNullOrWhiteSpace(note)
            ? $"Operator {normalised.ToLowerInvariant()} the cross-domain recommendation."
            : note.Trim();

        _audit.Record(
            actor: ActorName(),
            category: "Cross-Domain Reasoning",
            action: normalised,
            subject: string.IsNullOrWhiteSpace(recId) ? "REC-UNKNOWN" : recId.Trim(),
            reasoning: string.IsNullOrWhiteSpace(headline) ? reasoning : $"{reasoning} · {headline.Trim()}",
            source: "Human operator",
            approvalState: normalised,
            impact: string.IsNullOrWhiteSpace(impact) ? "—" : impact.Trim());

        TempData[normalised == "Rejected" ? "Warning" : "Success"] =
            $"Decision recorded: {normalised}. The recommendation is decision-support only and is not automatically executed.";
        return Redirect("/reasoning");
    }

    private string ActorName()
    {
        var name = User?.Identity?.Name;
        return string.IsNullOrWhiteSpace(name) ? "Demo operator" : name;
    }
}

/// <summary>
/// Read-only view over the immutable decision audit trail: every AI recommendation and
/// every state-changing decision, with who / what / when / why and quantified impact.
/// </summary>
[Authorize(Policy = Policies.CanAccessGeminiAgent)]
public class DecisionAuditController : Controller
{
    private readonly IDecisionAuditService _audit;

    public DecisionAuditController(IDecisionAuditService audit) => _audit = audit;

    [HttpGet("/decision-audit")]
    [HttpGet("/audit-trail")]
    public IActionResult Index()
    {
        ViewBag.Total = _audit.Count;
        return View(_audit.Recent(200));
    }
}
